2023-04-11 01:02:38,826 TADA INFO starting test `ldmsd_auth_test`
2023-04-11 01:02:38,826 TADA INFO   test-id: c20f522d6d32ed84d29d38335f04eca5479bc26ae5b92eda3b9ab94c9dba083f
2023-04-11 01:02:38,826 TADA INFO   test-suite: LDMSD
2023-04-11 01:02:38,826 TADA INFO   test-name: ldmsd_auth_test
2023-04-11 01:02:38,826 TADA INFO   test-user: narate
2023-04-11 01:02:38,826 TADA INFO   commit-id: 94a9b7ad0a9ffdf9152fdb494060db1352ad8238
2023-04-11 01:02:38,827 __main__ INFO -- Get or create the cluster --
2023-04-11 01:02:56,957 __main__ INFO -- Start daemons --
2023-04-11 01:03:15,788 __main__ INFO ... wait a bit to make sure ldmsd's are up
2023-04-11 01:03:20,920 TADA INFO assertion 1, root@agg-2(dom3) ldms_ls to agg-2:10000: see all sets, passed
2023-04-11 01:03:21,037 TADA INFO assertion 2, user@agg-2(dom3) ldms_ls to agg-2:10000: see only meminfo, passed
2023-04-11 01:03:21,149 TADA INFO assertion 3, root@headnode(dom4) ldms_ls to agg-2:10001: see all sets, passed
2023-04-11 01:03:21,261 TADA INFO assertion 4, user@headnode(dom4) ldms_ls to agg-2:10001: see only meminfo, passed
2023-04-11 01:03:21,364 TADA INFO assertion 5, root@headnode(dom4) ldms_ls to agg-11:10000: unexpected result: ['Tue Apr 11 01:03:21 2023:    ERROR: auth_munge: munge_decode() failed. Invalid credential', 'Connection failed/rejected.'], failed
2023-04-11 01:03:21,365 TADA INFO test ldmsd_auth_test ended
