2023-07-05 00:55:24,126 TADA INFO starting test `papi_sampler_test`
2023-07-05 00:55:24,127 TADA INFO   test-id: dea19c1c6aa8f2350307fce9fb49ac86bb1a94bba2a1a254d52795d36850e61c
2023-07-05 00:55:24,127 TADA INFO   test-suite: LDMSD
2023-07-05 00:55:24,127 TADA INFO   test-name: papi_sampler_test
2023-07-05 00:55:24,127 TADA INFO   test-user: narate
2023-07-05 00:55:24,127 TADA INFO   commit-id: 636a1c6eed94acbb98f830d7507cbfe1ed9a92a0
2023-07-05 00:55:24,127 __main__ INFO -- Get or create the cluster --
2023-07-05 00:55:29,544 __main__ INFO -- Start daemons --
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.35/containers/7349c6e37467e606bfb8bda18402568ddb86efd5cc1b60415e21e83a956f343f/exec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "papi_sampler_test", line 257, in <module>
    cluster.start_daemons()
  File "/home/narate/cron/ldms-test/LDMS_Test.py", line 1998, in start_daemons
    cont.start_daemons()
  File "/home/narate/cron/ldms-test/LDMS_Test.py", line 1260, in start_daemons
    fn(**daemon)
  File "/home/narate/cron/ldms-test/LDMS_Test.py", line 1003, in start_ldmsd
    cond_timedwait(_check_listen, 5)
  File "/home/narate/cron/ldms-test/LDMS_Test.py", line 2604, in cond_timedwait
    if cond():
  File "/home/narate/cron/ldms-test/LDMS_Test.py", line 1001, in _check_listen
    rc, out = self.exec_run(grp_cmd)
  File "/home/narate/cron/ldms-test/runtime/docker.py", line 144, in exec_run
    return self._exec_run(cmd, environment=env, user=user)
  File "/home/narate/cron/ldms-test/runtime/docker.py", line 148, in _exec_run
    (rc, out) = self.obj.exec_run(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/docker/models/containers.py", line 196, in exec_run
    workdir=workdir,
  File "/usr/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/docker/api/exec_api.py", line 80, in exec_create
    return self._result(res, True)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("Container 7349c6e37467e606bfb8bda18402568ddb86efd5cc1b60415e21e83a956f343f is not running")
2023-07-05 00:55:35,479 __main__ INFO -- Finishing Test --
2023-07-05 00:55:35,480 TADA INFO assertion 0, ldmsd has started: skipped
2023-07-05 00:55:35,480 TADA INFO assertion 1, Non-papi job does not create set: skipped
2023-07-05 00:55:35,480 TADA INFO assertion 1.1, Non-papi job is submitted: skipped
2023-07-05 00:55:35,480 TADA INFO assertion 1.2, Non-papi job is running before ldms_ls: skipped
2023-07-05 00:55:35,480 TADA INFO assertion 1.3, Non-papi job is running after ldms_ls: skipped
2023-07-05 00:55:35,481 TADA INFO assertion 2, papi job creates set: skipped
2023-07-05 00:55:35,481 TADA INFO assertion 2.1, Events in papi job set created according to config file: skipped
2023-07-05 00:55:35,481 TADA INFO assertion 2.2, Schema name is set accordingly: skipped
2023-07-05 00:55:35,481 TADA INFO assertion 2.3, PAPI set has correct job_id: skipped
2023-07-05 00:55:35,481 TADA INFO assertion 2.4, PAPI set has correct task_pids: skipped
2023-07-05 00:55:35,481 TADA INFO assertion 3, papi job creates set: skipped
2023-07-05 00:55:35,482 TADA INFO assertion 3.1, Events in papi job set created according to config file: skipped
2023-07-05 00:55:35,482 TADA INFO assertion 3.2, Schema name is set accordingly: skipped
2023-07-05 00:55:35,482 TADA INFO assertion 3.3, PAPI set has correct job_id: skipped
2023-07-05 00:55:35,482 TADA INFO assertion 3.4, PAPI set has correct task_pids: skipped
2023-07-05 00:55:35,482 TADA INFO assertion 4, Multiple, concurrent jobs results in concurrent, multiple sets: skipped
2023-07-05 00:55:35,482 TADA INFO assertion 6, PAPI set persists within `job_expiry` after job exited: skipped
2023-07-05 00:55:35,483 TADA INFO assertion 7, PAPI set is deleted after `2.2 x job_expiry` since job exited: skipped
2023-07-05 00:55:35,483 TADA INFO assertion 8, Missing config file attribute is logged: skipped
2023-07-05 00:55:35,483 TADA INFO assertion 9, Bad config file is logged: skipped
2023-07-05 00:55:35,483 TADA INFO test papi_sampler_test ended
2023-07-05 00:55:35,483 __main__ INFO -- Cleaning up files --
2023-07-05 00:55:35,483 __main__ INFO -- Removing the virtual cluster --
